import fs from 'fs';
import path from 'path';

function read(relPath: string): string {
  return fs.readFileSync(path.join(process.cwd(), relPath), 'utf8');
}

describe('cheer stabilization guards', () => {
  test('thank handler validates malformed json and cheerId mismatch', () => {
    const src = read('backend/services/cheer/thank/index.ts');
    expect(src).toContain('INVALID_JSON_BODY');
    expect(src).toContain('CHEER_ID_MISMATCH');
    expect(src).toContain('const cheerId = pickFirstDefinedString(cheerIdFromPath, cheerIdFromBody);');
    expect(src).toContain("ConditionExpression: '(attribute_not_exists(isThanked) OR isThanked = :false) AND receiverId = :receiverId'");
    expect(src).toContain('ConditionalCheckFailedException');
    expect(src).toContain('receiverId = :receiverId');
    expect(src).toContain('cheerIdFromPath');
    expect(src).toContain('cheerIdFromBody');
    expect(src).toContain('INVALID_CHEER_ID');
    expect(src).toContain('INVALID_CHEER_ID_FORMAT');
    expect(src).toContain('if (cheerIdFromPath && !isUuidV4(cheerIdFromPath)) {');
    expect(src).toContain('if (cheerIdFromBody && !isUuidV4(cheerIdFromBody)) {');
    expect(src).toContain('UUID_V4_REGEX');
    expect(src).toContain('function isUuidV4(value: string): boolean {');
    expect(src).toContain('JSON 객체여야 합니다');
    expect(src).toContain('let body: JsonObject = {};');
    expect(src).toContain('const parsedBody: unknown = JSON.parse(event.body);');
    expect(src).toContain('function isJsonObject(value: unknown): value is JsonObject {');
    expect(src).toContain('if (!isJsonObject(parsedBody)) {');
    expect(src).toContain('cheerIdFromPathRaw');
    expect(src).toContain('const normalizedPathCheerId = normalizeString(cheerIdFromPathRaw);');
    expect(src).toContain('if (cheerIdFromPathRaw !== undefined && !normalizedPathCheerId) {');
    expect(src).toContain('const cheerIdFromPath = normalizedPathCheerId;');
    expect(src).toContain('const normalizedBodyCheerId = normalizeString(cheerIdFromBodyRaw);');
    expect(src).toContain('const hasPathCheerIdValue = hasDefinedValue(normalizedPathCheerId);');
    expect(src).toContain('if (cheerIdFromBodyRaw !== undefined && !normalizedBodyCheerId) {');
    expect(src).toContain('const cheerIdFromBody = normalizedBodyCheerId;');
    expect(src).toContain("const hasBodyCheerIdField = hasOwnKey(body, 'cheerId');");
    expect(src).toContain('cheerIdFromBodyRaw');
    expect(src).toContain('.trim()');
    expect(src).toContain('conditional failure recheck error');
    expect(src).toContain('function normalizeString(value: unknown): string | undefined {');
    expect(src).toContain('function hasErrorName(value: unknown, expectedName: string): boolean {');
    expect(src).toContain('function isConditionalCheckFailed(error: unknown): boolean');
    expect(src).toContain('return hasErrorName(error, CONDITIONAL_CHECK_FAILED_EXCEPTION);');
    expect(src).toContain('if (isConditionalCheckFailed(error)) {');
    expect(src).toContain('} catch (error: unknown) {');
    expect(src).toContain('resolvedCheerId');
    expect(src).toContain('resolvedThankRouteMode');
    expect(src).toContain('CHEER_API_V2_CONTRACT');
    expect(src).toContain('LEGACY_THANK_ROUTE_DISABLED');
    expect(src).toContain('Blocked legacy thank request because CHEER_API_V2_CONTRACT is enabled');
    expect(src).toContain('if (shouldBlockLegacyRoute(CHEER_API_V2_CONTRACT, hasPathCheerIdValue)) {');
    expect(src).toContain('hasPathCheerId: hasPathCheerIdValue');
    expect(src).toContain('hasBodyCheerId: hasBodyCheerIdField');
    expect(src).toContain('const hasBodyCheerIdValue = hasDefinedValue(cheerIdFromBodyRaw);');
    expect(src).toContain('LEGACY_THANK_WARNING_HEADER');
    expect(src).toContain('if (shouldWarnLegacyRoute(CHEER_API_V2_CONTRACT, legacyBodyRouteAttempted)) {');
    expect(src).toContain('legacy thank route is deprecated; migrate to /cheers/{cheerId}/thank');
    expect(src).toContain('hasBodyCheerIdValue');
    expect(src).toContain('Legacy cheer thank contract is deprecated; use /cheers/{cheerId}/thank');
    expect(src).toContain('Deprecation');
    expect(src).toContain('Sunset');
    expect(src).toContain('CHEER_API_V2_SUNSET_AT');
    expect(src).toContain('DEFAULT_CHEER_API_V2_SUNSET_AT');
    expect(src).toContain('resolveCheerApiV2SunsetAt');
    expect(src).toContain('Invalid CHEER_API_V2_SUNSET_AT, fallback to default');
    expect(src).toContain('successor-version');
    expect(src).toContain('buildThankMigrationHeaders');
    expect(src).toContain('THANK_ROUTE_MODE_HEADER');
    expect(src).toContain("const CONDITIONAL_CHECK_FAILED_EXCEPTION = 'ConditionalCheckFailedException';");
    expect(src).toContain("type ThankRouteMode = 'canonical' | 'legacy'");
    expect(src).toContain('function isLegacyBodyRouteAttempt(cheerIdFromPathRaw: unknown, hasBodyCheerIdField: boolean): boolean {');
    expect(src).toContain('function hasOwnKey(target: JsonObject, key: string): boolean {');
    expect(src).toContain('function hasDefinedValue(value: unknown): boolean {');
    expect(src).toContain('function shouldWarnLegacyRoute(contractEnabled: boolean, legacyBodyRouteAttempted: boolean): boolean {');
    expect(src).toContain('function shouldBlockLegacyRoute(contractEnabled: boolean, hasPathCheerIdValue: boolean): boolean {');
    expect(src).toContain('function pickFirstDefinedString(...values: Array<string | undefined>): string | undefined {');
    expect(src).toContain('function resolveThankRouteMode(legacyBodyRouteAttempted: boolean): ThankRouteMode {');
    expect(src).toContain('type JsonObject = Record<string, any>;');
    expect(src).toContain('withThankRouteMode');
    expect(src).toContain('function response(statusCode: number, body: unknown, extraHeaders: Record<string, string> = {}): APIGatewayProxyResult {');
    expect(src).toContain('function canonicalRouteResponse');
    expect(src).toContain("return response(statusCode, body, withThankRouteMode({}, 'canonical'));");
    expect(src).toContain("withThankRouteMode(buildThankMigrationHeaders(), 'legacy')");
    expect(src).toContain('? withThankRouteMode(buildThankMigrationHeaders(), thankRouteMode)');
    expect(src).toContain(': withThankRouteMode({}, thankRouteMode);');
    expect(src).toContain('return blockedLegacyResponse();');
    expect(src).toContain('const legacyBodyRouteAttempted = isLegacyBodyRouteAttempt(cheerIdFromPathRaw, hasBodyCheerIdField);');
    expect(src).toContain('const thankRouteMode = resolveThankRouteMode(legacyBodyRouteAttempted);');
    expect(src).toContain('thankRouteMode,');
    expect(src).toContain('const legacyAwareBadRequest = (body: Record<string, string>) => response(400, body, migrationHeaders);');
    expect(src).toContain('const blockedLegacyResponse = () => response(400, {');
    expect(src).toContain('const requestUserId = event.requestContext.authorizer?.jwt?.claims?.sub as string | undefined;');
    expect(src).toContain('const resolvedRouteModeHeaders = () => withThankRouteMode({}, resolvedThankRouteMode);');
    expect(src).toContain('const resolvedRouteModeResponse = (statusCode: number, body: JsonObject) =>');
    expect(src).toContain('if (latest.Item.receiverId !== requestUserId) {');
    expect(src).toContain('return resolvedRouteModeResponse(500, {');
    expect(src).toContain('LEGACY_THANK_WARNING_HEADER');
  });

  test('use-ticket handler has claim/finalize and state-aware recovery', () => {
    const src = read('backend/services/cheer/use-ticket/index.ts');
    expect(src).toContain("UpdateExpression: 'SET #status = :processing");
    expect(src).toContain("ConditionExpression: '#status = :available AND userId = :userId'");
    expect(src).toContain('createdCheerCount');
    expect(src).toContain('INVALID_TICKET_EXPIRY');
    expect(src).toContain('INVALID_TICKET_DELTA');
    expect(src).toContain('Number.isInteger(parsedDelta)');
    expect(src).toContain('0 이상의 정수여야 합니다');
    expect(src).toContain("const challengeId = typeof ticket.challengeId === 'string' ? ticket.challengeId.trim() : ''");
    expect(src).toContain('message: z.string().trim().min(1).max(200)');
    expect(src).toContain('USE_TICKET_POST_CLAIM_PARTIAL_FAILURE');
    expect(src).toContain("UpdateExpression: 'SET #status = :available REMOVE processingAt, processingToken'");
    expect(src).toContain('ConditionalCheckFailedException');
    expect(src).toContain('TICKET_CLAIM_FAILED');
    expect(src).toContain('TICKET_RELEASE_FAILED');
  });

  test('get-my-cheers sanitizes query params and uses allSettled for read sync', () => {
    const src = read('backend/services/cheer/get-my-cheers/index.ts');
    expect(src).toContain("const rawType = (params.type || 'received').trim().toLowerCase();");
    expect(src).toContain("const type = rawType === 'sent' ? 'sent' : 'received'");
    expect(src).toContain('/^\\d+$/');
    expect(src).toContain('Math.min(100, Math.max(1, parsedLimit))');
    expect(src).toContain('Promise.allSettled');
    expect(src).toContain('receiverId = :receiverId');
    expect(src).toContain('cheer.readAt = readAt');
    expect(src).toContain('readAt: cheer.readAt ?? null');
    expect(src).toContain('Failed to mark cheer as read');
    expect(src).toContain('PromiseRejectedResult');
    expect(src).toContain('ConditionalCheckFailedException');
    expect(src).toContain('Cheer already marked as read by concurrent request');
    expect(src).toContain('cheer.readAt = cheer.readAt ?? readAt');
    expect(src).toContain('reason');
  });

  test('get-profile computes available tickets with paginated query count', () => {
    const src = read('backend/services/auth/get-profile/index.ts');
    expect(src).toContain('USER_CHEER_TICKETS_TABLE');
    expect(src).toContain("IndexName: 'userId-status-index'");
    expect(src).toContain('lastEvaluatedKey');
    expect(src).toContain('const pageCount = Number(ticketResult.Count || 0)');
    expect(src).toContain('totalCount += Number.isFinite(pageCount) ? Math.max(0, Math.floor(pageCount)) : 0');
    expect(src).toContain('fallback to user.cheerTickets');
    expect(src).toContain('Number.isFinite(fallbackCheerTickets)');
    expect(src).toContain('Math.max(0, Math.floor(fallbackCheerTickets))');
  });

  test('infra keeps new thank route and legacy compatibility route', () => {
    const stack = read('infra/stacks/cheer-stack.ts');
    expect(stack).toContain("path: '/cheers/{cheerId}/thank'");
    expect(stack).toContain("path: '/cheer/thank'");
    expect(stack).toContain('CHEER_API_V2_CONTRACT');
    expect(stack).toContain('CHEER_API_V2_SUNSET_AT');
  });

  test('cheer stack wires stats and interaction endpoints', () => {
    const stack = read('infra/stacks/cheer-stack.ts');
    expect(stack).toContain("path: '/cheers/stats'");
    expect(stack).toContain("path: '/cheers/{cheerId}/reply'");
    expect(stack).toContain("path: '/cheers/{cheerId}/reaction'");
    expect(stack).toContain('CheerStatsFn');
    expect(stack).toContain('CheerReplyFn');
    expect(stack).toContain('CheerReactFn');
    expect(stack).toContain('challengesTable.grantReadData(cheerStatsFn)');
    expect(stack).toContain('userChallengesTable.grantReadData(cheerStatsFn)');
    expect(stack).toContain('CHEER_STATS_TABLE');
    expect(stack).toContain('CheerStatsMaterializerFn');
    expect(stack).toContain('CheerStatsMaterializerSchedule');
    expect(stack).toContain('stats-materializer/index.ts');
    expect(stack).toContain('CHEER_STATS_MATERIALIZER_MAX_RETRIES');
    expect(stack).toContain('CHEER_STATS_MATERIALIZER_SCHEDULE_MINUTES');
    expect(stack).toContain('CHEER_STATS_MATERIALIZER_TOTAL_SEGMENTS');
    expect(stack).toContain('CHEER_STATS_MATERIALIZER_MAX_SCAN_PAGES');
    expect(stack).toContain('CHEER_STATS_MATERIALIZER_SCAN_PAGE_SIZE');
    expect(stack).toContain('CheerStatsMaterializerOrchestrator');
    expect(stack).toContain('CheerStatsMaterializerSegmentMap');
    expect(stack).toContain('CheerStatsMaterializerInvokeTask');
    expect(stack).toContain('SfnStateMachine');
    expect(stack).toContain('RuleTargetInput.fromObject');
    expect(stack).toContain('segments: materializerSegments');
    expect(stack).toContain('addRetry');
    expect(stack).toContain('CheerStatsMaterializerOrchestratorFailedAlarm');
    expect(stack).toContain('CheerStatsMaterializerExecutionFailedEventRule');
    expect(stack).toContain("status: ['FAILED', 'TIMED_OUT', 'ABORTED']");
    expect(stack).toContain('new SnsTopic(snsTopic)');
    expect(stack).toContain('materializerStateMachine.metricFailed');
    expect(stack).toContain('RuleTargetInput.fromObject');
    expect(stack).toContain('segmentIndex');
    expect(stack).toContain('totalSegments');
    expect(stack).toContain('CHEER_RATE_LIMITS_TABLE');
    expect(stack).toContain('CheerRateLimitsTableRef');
    expect(stack).toContain('CheerRateLimitsTableRefForReact');
    expect(stack).toContain('createErrorAlarm');
    expect(stack).toContain('CheerReplyError');
    expect(stack).toContain('CheerReactError');
    expect(stack).toContain('CheerStatsError');
    expect(stack).toContain('Reply cheer error');
    expect(stack).toContain('React cheer error');
    expect(stack).toContain('Get cheer stats error');
    expect(stack).toContain('CheerOpsDashboard');
    expect(stack).toContain('Dashboard');
    expect(stack).toContain('buildCheerOpsWidgetRows');
    expect(stack).toContain('dashboardRows.forEach');
    expect(stack).toContain('CheerStatsBucketedSource');
    expect(stack).toContain('CheerStatsRealtimeFallbackSource');
    expect(stack).toContain('CheerReplyRequest');
    expect(stack).toContain('CheerReplySuccess');
    expect(stack).toContain('CheerReplyClientError');
    expect(stack).toContain('CheerReactRequest');
    expect(stack).toContain('CheerReactSuccess');
    expect(stack).toContain('CheerReactClientError');
    expect(stack).toContain('CheerStatsRequest');
    expect(stack).toContain('CheerStatsSuccess');
    expect(stack).toContain("source: 'bucketed'");
    expect(stack).toContain("source: 'realtime_fallback'");
  });


  test('dashboard widget template module keeps cheer ops widget definitions', () => {
    const src = read('infra/stacks/observability/cheer-dashboard-widgets.ts');
    expect(src).toContain('buildCheerOpsWidgetRows');
    expect(src).toContain('Cheer Error Count (5m)');
    expect(src).toContain('Cheer Handler Latency p95');
    expect(src).toContain('Cheer Stats Source Mix (5m)');
    expect(src).toContain('Materializer Invocations/Errors');
    expect(src).toContain('Materializer Orchestrator (started/succeeded/failed)');
    expect(src).toContain('Reply Traffic Split (req/success/429)');
    expect(src).toContain('React Traffic Split (req/success/429)');
    expect(src).toContain('Stats Traffic Split (req/success/5xx)');
  });

  test('stats handler supports period/day/week/month/challenge filters', () => {
    const src = read('backend/services/cheer/stats/index.ts');
    expect(src).toContain("const period = (params.period || 'all').trim().toLowerCase();");
    expect(src).toContain("if (period === 'challenge' && !challengeId)");
    expect(src).toContain('toIsoRange(period');
    expect(src).toContain("collectByIndex('senderId-index'");
    expect(src).toContain("collectByIndex('receiverId-index'");
    expect(src).toContain('repliedCount');
    expect(src).toContain('reactionCount');
    expect(src).toContain('validateChallengeAccess');
    expect(src).toContain('CHALLENGE_NOT_FOUND');
    expect(src).toContain('CHALLENGE_ACCESS_DENIED');
    expect(src).toContain('TableName: process.env.CHALLENGES_TABLE!');
    expect(src).toContain('TableName: process.env.USER_CHALLENGES_TABLE!');
    expect(src).toContain('Get cheer stats request received');
    expect(src).toContain('Get cheer stats success');
    expect(src).toContain('latencyMs');
    expect(src).toContain('tryLoadBucketedStats');
    expect(src).toContain('CHEER_STATS_TABLE');
    expect(src).toContain("source: 'bucketed'");
    expect(src).toContain("source: 'realtime_fallback'");
    expect(src).toContain('resolveStatsBucketSk');
    expect(src).toContain('source: bucketed.source');
    expect(src).toContain("source: 'realtime_fallback'");
  });


  test('widget catalog docs are documented', () => {
    const catalog = read('docs/cheer-observability-widget-catalog.md');
    expect(catalog).toContain('Cheer Error Count (5m)');
    expect(catalog).toContain('Cheer Handler Latency p95');
    expect(catalog).toContain('Materializer Orchestrator (started/succeeded/failed)');
    expect(catalog).toContain('Reply Traffic Split (req/success/429)');
    expect(catalog).toContain('infra/stacks/observability/cheer-dashboard-widgets.ts');

    const runbook = read('docs/cheer-stats-materializer-runbook.md');
    expect(runbook).toContain('cheer-observability-widget-catalog.md');
  });

  test('materializer runbook and backfill scripts are documented', () => {
    const runbook = read('docs/cheer-stats-materializer-runbook.md');
    expect(runbook).toContain('fromIso');
    expect(runbook).toContain('toIso');
    expect(runbook).toContain('ISO-8601');
    expect(runbook).toContain('fromIso <= toIso');
    expect(runbook).toContain('dryRun');
    expect(runbook).toContain('maxRetries');
    expect(runbook).toContain('0 이상');
    expect(runbook).toContain('totalSegments');
    expect(runbook).toContain('segmentIndex');
    expect(runbook).toContain('failedSegments');
    expect(runbook).toContain('orchestratorArn');
    expect(runbook).toContain('segmentIndex < totalSegments');
    expect(runbook).toContain('totalSegments');
    expect(runbook).toContain('maxScanPages');
    expect(runbook).toContain('1 이상');
    expect(runbook).toContain('scanPageSize');
    expect(runbook).toContain('1~1000');
    expect(runbook).toContain('scripts/cheer-stats-backfill.sh');
    expect(runbook).toContain('scripts/cheer-stats-backfill.ps1');

    const sh = read('scripts/cheer-stats-backfill.sh');
    expect(sh).toContain('--stage');
    expect(sh).toContain('--dry-run');
    expect(sh).toContain('--from');
    expect(sh).toContain('--to');
    expect(sh).toContain('--from must be an ISO-8601 datetime string');
    expect(sh).toContain('--to must be an ISO-8601 datetime string');
    expect(sh).toContain('--from must be less than or equal to --to');
    expect(sh).toContain('--total-segments');
    expect(sh).toContain('--segment-index');
    expect(sh).toContain('--failed-segments');
    expect(sh).toContain('--orchestrator-arn');
    expect(sh).toContain('--segment-index requires --total-segments');
    expect(sh).toContain('--failed-segments requires --total-segments');
    expect(sh).toContain('--max-retries must be a non-negative integer');
    expect(sh).toContain('--segment-index must be less than --total-segments');
    expect(sh).toContain('start-execution');
    expect(sh).toContain('--max-scan-pages');
    expect(sh).toContain('--max-scan-pages must be >= 1');
    expect(sh).toContain('--scan-page-size');
    expect(sh).toContain('--scan-page-size must be between 1 and 1000');

    const ps1 = read('scripts/cheer-stats-backfill.ps1');
    expect(ps1).toContain('$Stage');
    expect(ps1).toContain('$DryRun');
    expect(ps1).toContain('$FromIso');
    expect(ps1).toContain('$ToIso');
    expect(ps1).toContain('-FromIso must be an ISO-8601 datetime string');
    expect(ps1).toContain('-ToIso must be an ISO-8601 datetime string');
    expect(ps1).toContain('-FromIso must be less than or equal to -ToIso');
    expect(ps1).toContain('$TotalSegments');
    expect(ps1).toContain('$SegmentIndex');
    expect(ps1).toContain('$FailedSegments');
    expect(ps1).toContain('$OrchestratorArn');
    expect(ps1).toContain('-SegmentIndex requires -TotalSegments');
    expect(ps1).toContain('-FailedSegments requires -TotalSegments');
    expect(ps1).toContain('-MaxRetries must be >= 0');
    expect(ps1).toContain('-SegmentIndex must be less than -TotalSegments');
    expect(ps1).toContain('start-execution');
    expect(ps1).toContain('$MaxScanPages');
    expect(ps1).toContain('-MaxScanPages must be >= 1');
    expect(ps1).toContain('$ScanPageSize');
    expect(ps1).toContain('-ScanPageSize must be between 1 and 1000');
  });

  test('stats materializer scans cheers and writes bucketed summaries', () => {
    const src = read('backend/services/cheer/stats-materializer/index.ts');
    expect(src).toContain('scanAllCheers');
    expect(src).toContain('buildStatsDocuments');
    expect(src).toContain('batchWriteStats');
    expect(src).toContain('BatchWriteCommand');
    expect(src).toContain('Cheer stats materializer finished');
    expect(src).toContain("challenge#${challengeId}#all");
    expect(src).toContain('owner#');
    expect(src).toContain('writeChunkWithRetry');
    expect(src).toContain('UnprocessedItems');
    expect(src).toContain('maxRetries');
    expect(src).toContain('dryRun');
    expect(src).toContain('fromIso');
    expect(src).toContain('toIso');
    expect(src).toContain('resolveScanOptions');
    expect(src).toContain('totalSegments');
    expect(src).toContain('segmentIndex');
    expect(src).toContain('maxScanPages');
    expect(src).toContain('scanPageSize');
    expect(src).toContain('scannedPages');
    expect(src).toContain('truncated');
    expect(src).toContain('Cheer stats materializer retrying unprocessed items');
  });

  test('shared rate-limit helper supports atomic table window key strategy', () => {
    const src = read('backend/services/cheer/rate-limit.ts');
    expect(src).toContain('acquireRateLimitSlot');
    expect(src).toContain('rateKey');
    expect(src).toContain('computeSlidingUsage');
    expect(src).toContain('sliding_window_approx');
    expect(src).toContain('token_bucket_approx');
    expect(src).toContain('BatchGetCommand');
    expect(src).toContain('requestCount = :expectedCurrent');
    expect(src).toContain('tokenBalance = :expectedTokenBalance');
    expect(src).toContain('CHEER_RATE_LIMIT_STRATEGY');
    expect(src).toContain("mode: 'atomic_table'");
    expect(src).toContain("mode: 'disabled'");
  });

  test('reply and react handlers enforce receiver-only interaction and idempotency', () => {
    const replySrc = read('backend/services/cheer/reply/index.ts');
    expect(replySrc).toContain('replyMessage');
    expect(replySrc).toContain('attribute_not_exists(replyMessage) AND receiverId = :receiverId');
    expect(replySrc).toContain('ALREADY_REPLIED');
    expect(replySrc).toContain('checkReplyRateLimit');
    expect(replySrc).toContain('checkReplyRateLimitFallback');
    expect(replySrc).toContain('acquireRateLimitSlot');
    expect(replySrc).toContain('CHEER_RATE_LIMITS_TABLE');
    expect(replySrc).toContain('scan_fallback');
    expect(replySrc).toContain('REPLY_RATE_LIMIT_EXCEEDED');
    expect(replySrc).toContain('Cheer reply request received');
    expect(replySrc).toContain('Cheer reply success');

    const reactSrc = read('backend/services/cheer/react/index.ts');
    expect(reactSrc).toContain('ALLOWED_REACTIONS');
    expect(reactSrc).toContain('attribute_not_exists(reactionType) AND receiverId = :receiverId');
    expect(reactSrc).toContain('ALREADY_REACTED');
    expect(reactSrc).toContain('checkReactionRateLimit');
    expect(reactSrc).toContain('checkReactionRateLimitFallback');
    expect(reactSrc).toContain('acquireRateLimitSlot');
    expect(reactSrc).toContain('CHEER_RATE_LIMITS_TABLE');
    expect(reactSrc).toContain('scan_fallback');
    expect(reactSrc).toContain('REACTION_RATE_LIMIT_EXCEEDED');
    expect(reactSrc).toContain('Cheer reaction request received');
    expect(reactSrc).toContain('Cheer reaction success');
  });

});
